### ISSUE TITLE
Supporting multiple value types

### ISSUE THREAD

**Issue by saidooubella** [parrt/simple-virtual-machine#3]
This is just a question.

What if I want to support multiple value types beside integers in my bytecode VM.

• My first attempt was to create a Value interface and representing each type by a class that implement the Value interface, the problem is during the execution a lot of allocations happens (e.g. iterating 10000 times create 10000 object).

`
public interface Value {}
`
`
public class Int implement Value {}
`

• My second attempt was to use a byte array to store those types (int, long, float, double and boolean) to stick with primitives, but I run into a lot of limitations because of this approach. I've used this approach just to minimize the allocations during the execution of the program to only initializing those byte arrays.

Anyway both worked but the first approach is super flexible and accept changes without breaking code, so I think I'll stick with it, but do you have any suggestions about how to do this in a performant way?

**Comment by parrt** [comment]
Hi. Sorry, I haven't looked at this project in years and I don't have time to dig in. :(

**Comment by saidooubella** [comment]
I am just asking in general not specifically for this project, I'm just interested in bytecode interpreters and I wanna know.

**Comment by parrt** [comment]
Sorry. yeah, I don't even have time to think...

**Comment by saidooubella** [comment]
Aah thank you for your time. I'm sorry for bothering you (≧▽≦).
